package com.example.StudentLibraryManagementSystem.Model;

import jakarta.persistence.*;

import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "authors")
public class Author {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id; // will be auto generated by the GeneratedValue annotation
    private String name; //will come from the postman
    private int age; //will come from the postman
    private int no_of_books; //it will automatically update while adding new books
    private String country; // will come from the postman

    //This will be the parent entity with respect to Book.
    //So setting the parent side mapping for getting the bidirectional relation
    @OneToMany(mappedBy = "author", cascade = CascadeType.ALL)
    private List<Book> books; //Because of one to many, there will be more than one books by the same Author.
    public Author() {
        this.books = new ArrayList<>(); // not mandatory. Spring boot will automatically initialize this list.
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getNo_of_books() {
        return no_of_books;
    }

    public void setNo_of_books(int no_of_books) {
        this.no_of_books = no_of_books;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Book> getBooks() {
        return books;
    }

    public void setBooks(List<Book> books) {
        this.books = books;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }
}
